DROP TABLE IF EXISTS manao_links;

CREATE TABLE `manao_links` (
  ID             INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  OLD_LINK    VARCHAR(255) NOT NULL UNIQUE,
  OLD_LINK_HTTP_STATUS    INT,
  NEW_LINK  VARCHAR(255) NOT NULL,
  NEW_LINK_HTTP_STATUS INT,
  XML_ID  VARCHAR(255) UNIQUE,
  DATE_MODIFY TIMESTAMP
);


--INSERT INTO manao_discount_view (DISCOUNT_ID, VIEW_TYPE) VALUES (6, 'CROSSED_OUT');